version: '3.7'

services:
  chatty-kafka:
    image: 'bitnami/kafka:latest'
    container_name: chatty-kafka
    networks:
      - my-network
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - 'KAFKA_ADVERTISED_LISTENER=PLAINTEXT://chatty-kafka:9092'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - my-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chatty-ms:
    build:
      context: ./chatty-ms
      dockerfile: Dockerfile
    container_name: chatty-ms
    networks:
      - my-network
    ports:
      - "8090:8090"
    depends_on:
      - chatty-kafka
      - postgres

  chatty-client:
    build:
      context: ./chatty-client
      dockerfile: Dockerfile
    container_name: chatty-client
    networks:
      - my-network
    ports:
      #- "3001:3001"
       - '80:80'
    depends_on:
      - chatty-ms

networks:
  my-network:  # Ensure this section is defined properly
    driver: bridge

volumes:
  postgres_data:
    driver: local
